---
title: "One-line Monte Carlo simulation"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: show
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r, include=FALSE}

# set default chunk options
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE)

# disable scientific notation
options(scipen = 999) 

```

# Simulate normal data

Draw data from a normally distributed population and plot it using `rnorm()`

```{r}

rnorm(n = 1000, m = 0, sd = 1) |> 
  hist()

```

# Fit a t test 

to the generated data

```{r}

set.seed(42)
t.test(rnorm(n = 50, m = 0, sd = 1), rnorm(n = 50, m = 0, sd = 1))

```

# Extract the p value

Fit a t test to generated data and extract the p value

```{r}

set.seed(42)
t.test(rnorm(n = 50, m = 0, sd = 1), rnorm(n = 50, m = 0, sd = 1))$p.value

```

# Do this generate-and-analyze many times

+ plot the p values

```{r}

res <- replicate(1000, t.test(rnorm(n = 50, m = 0, sd = 1), rnorm(n = 50, m = 0, sd = 1))$p.value)

res |> hist()

```

# Increase the number of iterations 

Why is the distribution more uniform?

```{r}

res <- replicate(100000, t.test(rnorm(n = 50, m = 0, sd = 1), rnorm(n = 50, m = 0, sd = 1))$p.value)

res |> hist()

```


